//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrimeTrackingSystem_CTS_.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CriminalGallery
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string AffectedOrganisation { get; set; }
        public string Reward { get; set; }
        public string CriminalImage { get; set; }
        public string Details { get; set; }
        public string CurrentDateTime { get; set; }
    }
}
