//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrimeTrackingSystem_CTS_.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CTSEntitiesClass : DbContext
    {
        public CTSEntitiesClass()
            : base("name=CTSEntitiesClass")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Contact> Contacts { get; set; }
        public virtual DbSet<CrimeComplain> CrimeComplains { get; set; }
        public virtual DbSet<CriminalGallery> CriminalGalleries { get; set; }
        public virtual DbSet<Event> Events { get; set; }
        public virtual DbSet<FAQ> FAQs { get; set; }
        public virtual DbSet<Feedback> Feedbacks { get; set; }
        public virtual DbSet<GeneralComplain> GeneralComplains { get; set; }
        public virtual DbSet<MissingPerson> MissingPersons { get; set; }
        public virtual DbSet<MissingValuable> MissingValuables { get; set; }
        public virtual DbSet<PoliceStation> PoliceStations { get; set; }
        public virtual DbSet<Signup> Signups { get; set; }
    }
}
