//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrimeTrackingSystem_CTS_.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CTSEntities : DbContext
    {
        public CTSEntities()
            : base("name=CTSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Contact> Contact { get; set; }
        public virtual DbSet<CrimeComplain> CrimeComplain { get; set; }
        public virtual DbSet<CriminalGallery> CriminalGallery { get; set; }
        public virtual DbSet<Events> Events { get; set; }
        public virtual DbSet<FAQ> FAQ { get; set; }
        public virtual DbSet<GeneralComplain> GeneralComplain { get; set; }
        public virtual DbSet<Login> Login { get; set; }
        public virtual DbSet<MissingPerson> MissingPerson { get; set; }
        public virtual DbSet<MissingValuable> MissingValuable { get; set; }
        public virtual DbSet<PoliceStation> PoliceStation { get; set; }
        public virtual DbSet<Signup> Signup { get; set; }
    }
}
