//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrimeTrackingSystem_CTS_.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;


    public partial class FAQ
    {
        public int Id { get; set; }

        [Required(ErrorMessage ="required")]
        public string Questions { get; set; }

        [Required(ErrorMessage = "required")]
        public string Answer { get; set; }
    }
}
