//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrimeTrackingSystem_CTS_.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Feedback
    {
        public int Id { get; set; }

        [DisplayName("Your name")]
        [Required]
        public string Yourname { get; set; }

        [DisplayName("E-mail")]
        [Required]
        [RegularExpression(@"^[\w-\.]+@([\w-]+\.)+[\w-]{2,4}$", ErrorMessage = "invalid e-mail id")]
        public string E_mail { get; set; }

        [DisplayName("Your thoughts")]
        [Required]
        [StringLength(150, ErrorMessage = "not more than 150 words")]
        public string Words { get; set; }
    }
}
