//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrimeTrackingSystem_CTS_.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GeneralComplain
    {
        public int Id { get; set; }
        public string Username { get; set; }
        public string PoliceStation { get; set; }
        public string Subject { get; set; }
        public string Details { get; set; }
        public string InvolvedPersons { get; set; }
        public string CurrentDateTime { get; set; }
        public string Status { get; set; }
    }
}
