//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrimeTrackingSystem_CTS_.Models
{
    public interface ISignup
    {
        string Address { get; set; }
        decimal Adhaar { get; set; }
        string Email { get; set; }
        string Gender { get; set; }
        string Lstatus { get; set; }
        string Mstatus { get; set; }
        string Password { get; set; }
        decimal Phone { get; set; }
        string Photo { get; set; }
        decimal Pincode { get; set; }
        int RegId { get; set; }
        string Role { get; set; }
        string Username { get; set; }
    }
}