//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrimeTrackingSystem_CTS_.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class MissingValuable
    {
        public int Id { get; set; }
        public string Username { get; set; }
        public string PoliceStationName { get; set; }
        public string ValuableType { get; set; }
        public string ValuableCost { get; set; }
        public string Suspect { get; set; }
        public string ReciptImage { get; set; }
        public string Details { get; set; }
        public string CurrentDateTime { get; set; }
        public string Status { get; set; }
    }
}
