//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrimeTrackingSystem_CTS_.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MissingPerson
    {
        public int Id { get; set; }
        public string Username { get; set; }
        public string PoliceStationName { get; set; }
        public string Person { get; set; }
        public string PersonPhone { get; set; }
        public string LastLocation { get; set; }
        public string PersonEmail { get; set; }
        public string Ransom { get; set; }
        public string Details { get; set; }
        public string PersonImage { get; set; }
        public string CurrentDateTime { get; set; }
        public string Status { get; set; }
    }
}
