//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrimeTrackingSystem_CTS_.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;
    
    public partial class PoliceStation
    {
        public int Id { get; set; }
        public string ChowkiIncharge { get; set; }
        public string PoliceStationName { get; set; }
        public string CUGNumberOne { get; set; }
        public string CUGNumberSecond { get; set; }
        public string Agent { get; set; }
        public string AgentPhone { get; set; }
        public string PoliceStationImage { get; set; }
    }
}
