//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrimeTrackingSystem_CTS_.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PoliceStation
    {
        public int Id { get; set; }
        public string ChowkiIncharge { get; set; }
        public string PoliceStation1 { get; set; }
        public decimal CUGNumberOne { get; set; }
        public decimal CUGNumberSecond { get; set; }
        public string Agent { get; set; }
        public decimal AgentPhone { get; set; }
        public string PoliceStationImage { get; set; }
    }
}
