//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrimeTrackingSystem_CTS_.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Signup
    {
        public int RegId { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public string Gender { get; set; }
        public decimal Pincode { get; set; }
        public string Address { get; set; }
        public string Mstatus { get; set; }
        public string Lstatus { get; set; }
        public decimal Adhaar { get; set; }
        public decimal Phone { get; set; }
        public string Photo { get; set; }
    }
}
